# Generated by Django 4.2 on 2023-04-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Women",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                ("content", models.TextField(blank=True, verbose_name="Текст статьи")),
                (
                    "photo",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "time_updat",
                    models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
                ),
                ("is_published", models.BooleanField(verbose_name="Публикация")),
            ],
        ),
    ]
