# Generated by Django 4.2 on 2023-04-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(related_name="quizzes", to="app.question"),
        ),
    ]
